### ISSUE TITLE
Latest versions are missing

### ISSUE THREAD

**Issue by jairbubbles** [jellyfin/jellyfin-skiasharp-native#2]
Jefflyfin is now using SkiaSharp 1.68.1 but the arm binaries are still in 1.68.0, I believe it's responsible for this bug: https://github.com/jellyfin/jellyfin/issues/2471

I'd be happy to help, is there some documentation how to update those?

**Comment by mark-monteiro** [comment]
I'm not familiar with this repo, but it looks like the version is specified in the build scripts [here](https://github.com/jellyfin/jellyfin-skiasharp-native/blob/master/Jellyfin.SkiaSharp.NativeAssets.LinuxMusl/compile-libSkiaSharp.sh#L6) and [here](https://github.com/jellyfin/jellyfin-skiasharp-native/blob/master/Jellyfin.SkiaSharp.NativeAssets.LinuxArm/cross-compile-libSkiaSharp.sh#L7). And the [latest version](https://github.com/mono/SkiaSharp/releases) of SkiaSharp is actually `1.68.1.1` not `1.68.1`.

The version in the `.nuspec` files will also need to be updated

**EDIT:** There is also documentation/guidelines on how to contribute code, that you can follow here if you are unfamiliar: https://jellyfin.org/docs/general/contributing/development.html

**Comment by jairbubbles** [comment]
Yep, I'm currently trying to compile on my computer the new binaries.
